//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2NET.V1.Items.Converters
{
    using System;

    using GW2NET.Common;
    using GW2NET.Items;
    using GW2NET.V1.Items;
    using GW2NET.V1.Items.Json;

    public sealed partial class GizmoConverter : IConverter<ItemDTO, Gizmo>
	{
	    private readonly ITypeConverterFactory<ItemDTO, Gizmo> converterFactory;

		public GizmoConverter(ITypeConverterFactory<ItemDTO, Gizmo> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException("converterFactory");
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        Gizmo IConverter<ItemDTO, Gizmo>.Convert(ItemDTO value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException("value");
    		}

			string discriminator = value.Gizmo == null ? null : value.Gizmo.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'Gizmo' (if any)
    	partial void Merge(Gizmo entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class GizmoConverter
		{
		    partial void Merge(Gizmo entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region ContainerKey
    /// <summary>Converts objects of type <see cref="ItemDTO"/> to objects of type <see cref="ContainerKey"/>.</summary>
    public sealed partial class ContainerKeyConverter : IConverter<ItemDTO, ContainerKey>
    {
	    /// <inheritdoc />
        public ContainerKey Convert(ItemDTO value, object state)
        {
    		var entity = new ContainerKey();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'ContainerKey' (if any)
    	partial void Merge(ContainerKey entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class ContainerKeyConverter
		{
		    partial void Merge(ContainerKey entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region DefaultGizmo
    /// <summary>Converts objects of type <see cref="ItemDTO"/> to objects of type <see cref="DefaultGizmo"/>.</summary>
    public sealed partial class DefaultGizmoConverter : IConverter<ItemDTO, DefaultGizmo>
    {
	    /// <inheritdoc />
        public DefaultGizmo Convert(ItemDTO value, object state)
        {
    		var entity = new DefaultGizmo();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'DefaultGizmo' (if any)
    	partial void Merge(DefaultGizmo entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class DefaultGizmoConverter
		{
		    partial void Merge(DefaultGizmo entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region RentableContractNpc
    /// <summary>Converts objects of type <see cref="ItemDTO"/> to objects of type <see cref="RentableContractNpc"/>.</summary>
    public sealed partial class RentableContractNpcConverter : IConverter<ItemDTO, RentableContractNpc>
    {
	    /// <inheritdoc />
        public RentableContractNpc Convert(ItemDTO value, object state)
        {
    		var entity = new RentableContractNpc();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'RentableContractNpc' (if any)
    	partial void Merge(RentableContractNpc entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class RentableContractNpcConverter
		{
		    partial void Merge(RentableContractNpc entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownGizmo
    /// <summary>Converts objects of type <see cref="ItemDTO"/> to objects of type <see cref="UnknownGizmo"/>.</summary>
    public sealed partial class UnknownGizmoConverter : IConverter<ItemDTO, UnknownGizmo>
    {
	    /// <inheritdoc />
        public UnknownGizmo Convert(ItemDTO value, object state)
        {
    		var entity = new UnknownGizmo();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownGizmo' (if any)
    	partial void Merge(UnknownGizmo entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class UnknownGizmoConverter
		{
		    partial void Merge(UnknownGizmo entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnlimitedConsumable
    /// <summary>Converts objects of type <see cref="ItemDTO"/> to objects of type <see cref="UnlimitedConsumable"/>.</summary>
    public sealed partial class UnlimitedConsumableConverter : IConverter<ItemDTO, UnlimitedConsumable>
    {
	    /// <inheritdoc />
        public UnlimitedConsumable Convert(ItemDTO value, object state)
        {
    		var entity = new UnlimitedConsumable();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnlimitedConsumable' (if any)
    	partial void Merge(UnlimitedConsumable entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class UnlimitedConsumableConverter
		{
		    partial void Merge(UnlimitedConsumable entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
