//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2NET.V2.Items.Converters
{
    using System;

    using GW2NET.Common;
    using GW2NET.Items;
	using ItemDTO = GW2NET.V2.Items.Json.ItemDTO;

    public sealed partial class ToolConverter : IConverter<ItemDTO, Tool>
	{
	    private readonly ITypeConverterFactory<ItemDTO, Tool> converterFactory;

		public ToolConverter(ITypeConverterFactory<ItemDTO, Tool> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException("converterFactory");
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        Tool IConverter<ItemDTO, Tool>.Convert(ItemDTO value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException("value");
    		}

			string discriminator = value.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'Tool' (if any)
    	partial void Merge(Tool entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class ToolConverter
		{
		    partial void Merge(Tool entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region SalvageTool
    /// <summary>Converts objects of type <see cref="ItemDTO"/> to objects of type <see cref="SalvageTool"/>.</summary>
    public sealed partial class SalvageToolConverter : IConverter<ItemDTO, Tool>
    {
	    /// <inheritdoc />
        public Tool Convert(ItemDTO value, object state)
        {
    		var entity = new SalvageTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'SalvageTool' (if any)
    	partial void Merge(SalvageTool entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class SalvageToolConverter
		{
		    partial void Merge(SalvageTool entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownTool
    /// <summary>Converts objects of type <see cref="ItemDTO"/> to objects of type <see cref="UnknownTool"/>.</summary>
    public sealed partial class UnknownToolConverter : IConverter<ItemDTO, Tool>
    {
	    /// <inheritdoc />
        public Tool Convert(ItemDTO value, object state)
        {
    		var entity = new UnknownTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownTool' (if any)
    	partial void Merge(UnknownTool entity, ItemDTO dto, object state);

		/*
		// Use this template
		public partial class UnknownToolConverter
		{
		    partial void Merge(UnknownTool entity, ItemDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
