//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2NET.Converter
{
    using System;
    using Common;
    using Skins;
    using SkinDTO = Json.SkinDTO;

    public sealed partial class GatheringToolSkinConverter : IConverter<Json.SkinDTO, GatheringToolSkin>
	{
	    private readonly ITypeConverterFactory<SkinDTO, GatheringToolSkin> converterFactory;

		public GatheringToolSkinConverter(ITypeConverterFactory<SkinDTO, GatheringToolSkin> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException("converterFactory");
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        GatheringToolSkin IConverter<SkinDTO, GatheringToolSkin>.Convert(SkinDTO value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException("value");
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'GatheringToolSkin' (if any)
    	partial void Merge(GatheringToolSkin entity, SkinDTO dto, object state);

		/*
		// Use this template
		public partial class GatheringToolSkinConverter
		{
		    partial void Merge(GatheringToolSkin entity, SkinDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region ForagingToolSkin
    /// <summary>Converts objects of type <see cref="SkinDTO"/> to objects of type <see cref="ForagingToolSkin"/>.</summary>
    public sealed partial class ForagingToolSkinConverter : IConverter<Json.SkinDTO, GatheringToolSkin>
    {
	    /// <inheritdoc />
        public GatheringToolSkin Convert(SkinDTO value, object state)
        {
    		var entity = new ForagingToolSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'ForagingToolSkin' (if any)
    	partial void Merge(ForagingToolSkin entity, SkinDTO dto, object state);

		/*
		// Use this template
		public partial class ForagingToolSkinConverter
		{
		    partial void Merge(ForagingToolSkin entity, SkinDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region LoggingToolSkin
    /// <summary>Converts objects of type <see cref="SkinDTO"/> to objects of type <see cref="LoggingToolSkin"/>.</summary>
    public sealed partial class LoggingToolSkinConverter : IConverter<Json.SkinDTO, GatheringToolSkin>
    {
	    /// <inheritdoc />
        public GatheringToolSkin Convert(SkinDTO value, object state)
        {
    		var entity = new LoggingToolSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'LoggingToolSkin' (if any)
    	partial void Merge(LoggingToolSkin entity, SkinDTO dto, object state);

		/*
		// Use this template
		public partial class LoggingToolSkinConverter
		{
		    partial void Merge(LoggingToolSkin entity, SkinDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region MiningToolSkin
    /// <summary>Converts objects of type <see cref="SkinDTO"/> to objects of type <see cref="MiningToolSkin"/>.</summary>
    public sealed partial class MiningToolSkinConverter : IConverter<Json.SkinDTO, GatheringToolSkin>
    {
	    /// <inheritdoc />
        public GatheringToolSkin Convert(SkinDTO value, object state)
        {
    		var entity = new MiningToolSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'MiningToolSkin' (if any)
    	partial void Merge(MiningToolSkin entity, SkinDTO dto, object state);

		/*
		// Use this template
		public partial class MiningToolSkinConverter
		{
		    partial void Merge(MiningToolSkin entity, SkinDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownGatheringToolSkin
    /// <summary>Converts objects of type <see cref="SkinDTO"/> to objects of type <see cref="UnknownGatheringToolSkin"/>.</summary>
    public sealed partial class UnknownGatheringToolSkinConverter : IConverter<Json.SkinDTO, GatheringToolSkin>
    {
	    /// <inheritdoc />
        public GatheringToolSkin Convert(SkinDTO value, object state)
        {
    		var entity = new UnknownGatheringToolSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownGatheringToolSkin' (if any)
    	partial void Merge(UnknownGatheringToolSkin entity, SkinDTO dto, object state);

		/*
		// Use this template
		public partial class UnknownGatheringToolSkinConverter
		{
		    partial void Merge(UnknownGatheringToolSkin entity, SkinDTO dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
