//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2DotNET.V1.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GW2DotNET.V1.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.guildwars2.com/v{0}/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build.json.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colors.json.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continents.json.
        /// </summary>
        internal static string Continents {
            get {
                return ResourceManager.GetString("Continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_details.json.
        /// </summary>
        internal static string EventDetails {
            get {
                return ResourceManager.GetString("EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event_names.json.
        /// </summary>
        internal static string EventNames {
            get {
                return ResourceManager.GetString("EventNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.json.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.json.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guild_details.json.
        /// </summary>
        internal static string GuildDetails {
            get {
                return ResourceManager.GetString("GuildDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item_details.json.
        /// </summary>
        internal static string ItemDetails {
            get {
                return ResourceManager.GetString("ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.json.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map_floor.json.
        /// </summary>
        internal static string MapFloor {
            get {
                return ResourceManager.GetString("MapFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map_names.json.
        /// </summary>
        internal static string MapNames {
            get {
                return ResourceManager.GetString("MapNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maps.json.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wvw/match_details.json.
        /// </summary>
        internal static string MatchDetails {
            get {
                return ResourceManager.GetString("MatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wvw/matches.json.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wvw/objective_names.json.
        /// </summary>
        internal static string ObjectiveNames {
            get {
                return ResourceManager.GetString("ObjectiveNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recipe_details.json.
        /// </summary>
        internal static string RecipeDetails {
            get {
                return ResourceManager.GetString("RecipeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recipes.json.
        /// </summary>
        internal static string Recipes {
            get {
                return ResourceManager.GetString("Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to world_names.json.
        /// </summary>
        internal static string WorldNames {
            get {
                return ResourceManager.GetString("WorldNames", resourceCulture);
            }
        }
    }
}
