// <auto-generated />

using System.Reflection;
using System.Resources;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("GW2.NET Compression")]
[assembly: AssemblyDescription("This library is used for inflating streams that were compressed using a deflation algorithm")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en")]