// <auto-generated />

using System.Reflection;
using System.Resources;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("GW2.NET")]
[assembly: AssemblyDescription("GW2.NET is an implementation of the Guild Wars 2 public API")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en")]